version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    #command: --storageEngine=wiredTiger
    restart: always
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
  uplancebot:
    container_name: uplancebot
    image: uplancebot:latest
    build: .
    restart: always
    environment:
      DB_HOST: "mongo"
      DB_PORT: "27017"
      DB_NAME: "uplancebot"
      DB_MAX_POOL_SIZE: "600"
      MIN_UPDATE_PERIOD: "180"
      DEBUG: "True"
    env_file: 
      - bot.env
    depends_on:
      - mongo
volumes:
  mongo-volume:
    driver: local

