alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: uplancebot-app
region: sgp
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: Goodsmileduck/uplancebot-public
  instance_count: 1
  instance_size_slug: basic-xxs
  name: uplancebot-public
  source_dir: /
  envs:
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: "mongo"
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: "27017"
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: "uplancebot"
  - key: DB_MAX_POOL_SIZE
    scope: RUN_AND_BUILD_TIME
    value: "300"
  - key: MIN_UPDATE_PERIOD
    scope: RUN_AND_BUILD_TIME
    value: "15"
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
- name: mongo
  image:
    registry_type: "DOCKER_HUB"
    registry: https://hub.docker.com/
    repository: mongo
    tag: "4.0"
  instance_count: 1
  instance_size_slug: basic-xxs
  internal_ports: [27017]
  

